title: Cayman theme
description: Expert DevOps professional with deep experience in cloud infrastructure, Linux operations, and security.
Justification:
show_downloads: true
theme: jekyll-theme-cayman
