title: Jay-Alexander Elliot resume website.
description: DevOps professional with deep experience in cloud infrastructure, Linux operations, and security.
Justification:
show_downloads: false
theme: jekyll-theme-cayman
